[toolchain]
anchor_version = "0.30.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mpl_core_anchor_wrapper = "EXMPLWxvGsyDuHMcnZHBnUN32RaoyVowkzhyXmAVxmEM"

[programs.devnet]
mpl_core_anchor_wrapper = "3xUZd5P2SaekdPjYWdPLtbDxLhGbWchMFezcHUh846Yd"

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "tests/programs/mpl_core.so"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
